" On Windows, also use ~/.vim instead of ~/vimfiles; 
" this makes synchronization across (heterogeneous) systems easier.
" See https://stackoverflow.com/a/53370672/1108891
if has('win32') || has('win64')
    let &runtimepath = substitute(&runtimepath, '\C\V' . escape($HOME.'/vimfiles', '\'), escape($HOME.'/.vim', '\&'), 'g')
    if exists('&packpath')
        let &packpath = &runtimepath
    endif
endif

filetype plugin indent on
syntax on

packloadall

au BufRead,BufNewFile *.ts setfiletype typescript
au BufRead,BufNewFile *.csv,*.dat setfiletype csv

" This is nice for vimdiff too `vim -d file1 file2`.
" Favorites include peachpuff, onedark, gruvbox, desert
colorscheme gruvbox

set tabstop=4
set shiftwidth=4
set softtabstop=0
set expandtab
set autoindent

set number

com! FormatJson %!jq "."

" For WSL, copy (write) highlighted text to .vimbuffer (and then to Windows clipboad)
vmap <C-c> y:new ~/.vimbuffer<CR>VGp:x<CR> \| :!cat ~/.vimbuffer \| clip.exe <CR><CR>
